### ISSUE TITLE
move chat to bottom on small screens

### ISSUE THREAD

**Issue by laopewastaken** [gregle/embedTwitchCSS#1]
hi,
there is an option to move chat to bottom on small screens (phones/tablets) instead of hide chat? im a noob in css so i cant figure it out :(

**Comment by gregle** [comment]
Yeah you totally can, you can manipulate the containers however you'd like the most important part are the relationship between the the stream iframe and the before element to maintain the 16:9 ratio.

You can check out an implementation of what you're looking for here: http://teamcatalyst.tv/streams
